akamatsu/views/common.py
# -*- coding: utf-8 -*-
#
# Akamatsu CMS
# https://github.com/rmed/akamatsu
#
# MIT License
#
# Copyright (c) 2020 Rafael Medina García <rafamedgar@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""This file contains common views."""

import os

from flask import Blueprint, current_app, make_response, send_from_directory
from werkzeug.utils import secure_filename

from akamatsu.models import FileUpload


bp_common = Blueprint('common', __name__)


@bp_common.route('/_uploads/<path:filename>')
def serve_file(filename):
    """Serve the given uploaded file.

    Args:
        filename (str): Relative file path.
    """
    fupload = FileUpload.get_by_path(filename)

    if not fupload:
        return make_response('', 404)

    return send_from_directory(
        current_app.config['UPLOADS_PATH'],
        filename,
        mimetype=fupload.mime
    )


@bp_common.route('/favicon.ico')
def favicon():
    """Serve favicon.

    This endpoint will return a 404 unless the `FAVICON_DIR` attribute
    is configured in the application and a "favicon.ico" file exists in
    that directory.

    Args:
        filename (str): Filename to serve.
    """
    fav_path = current_app.config.get('FAVICON_DIR')

    if not fav_path or not os.path.isdir(fav_path):
        return make_response('', 404)

    return send_from_directory(fav_path, 'favicon.ico')


@bp_common.route('/_favicon/<path:filename>')
def favicon_extras(filename):
    """Serve favicon related files.

    This endpoint will return a 404 unless the `FAVICON_DIR` attribute
    is configured in the application.

    Args:
        filename (str): Filename to serve.
    """
    fav_path = current_app.config.get('FAVICON_DIR')

    if not fav_path or not os.path.isdir(fav_path):
        return make_response('', 404)

    return send_from_directory(fav_path, secure_filename(filename))

akamatsu/templates/error.html
{% import "macros.html" as macros %}
{% extends "layout.html" %}

{% block title %}{{ title }}{% endblock %}
{% block mini %}{{ _('error') }}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="title is-1">{{ title }}</h1>
    <h2 class="subtitle is-2">{{ error_msg }}</h2>

    <div class="is-divider"></div>
</div>
{% endblock %}

akamatsu/templates/layout.html
{% import "macros.html" as macros %}

<!DOCTYPE HTML>
<html>
{% block html_head %}
<head>
    {# Favicon #}
    {% if config.get('FAVICON_DIR') and config.get('FAVICON_EXTRAS') %}
        {% for extra in config['FAVICON_EXTRAS'] %}
            <link rel="{{ extra['rel'] }}" type="{{ extra['type'] }}" sizes="{{ extra['sizes'] }}" href="{{ url_for('common.favicon_extras', filename=extra['file']) }}">
        {% endfor %}
    {% endif %}

    <title>{% block title %}{% endblock %} | {{ config['SITENAME'] }}</title>

    {# Minified CSS #}
    {% assets "css_pack" %}
        <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}"/>
    {% endassets %}

    {# Minified JS #}
    {% assets "js_pack" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {# Meta tags #}
    <meta charset="utf-8"/>
    <meta name="distribution" content="global"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta property="og:title" content="{{ self.title() }}"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="{{ request.url }}"/>
    <meta property="og:site_name" content="{{ config['SITENAME'] }}"/>

    {# Analytics #}
    {% if config.get('USE_ANALYTICS', False) %}
        {{ analytics }}
    {% endif %}

    {# CSRF token. Set flag in templates when needed #}
    {% if _include_csrf %}
        <meta name="csrf-token" content="{{ csrf_token() }}"/>
    {% endif %}

    {# Additional tags #}
    {% block head_extend %}{% endblock %}
</head>
{% endblock %}

{% block html_body %}
<body>
    {# Hero #}
    <section class="hero is-dark with-navbar">
        <div class="hero-body">
            <div class="container">
                {# Social links #}
                <div id="social-links">
                    {% for item in config.get('SOCIAL', []) %}
                        <a class="is-size-3" href="{{ item['link'] }}" target="_blank">
                            <i class="{{ item['glyph'] }}"></i>
                        </a>
                    {% endfor %}
                </div>
                <h1 class="title">{{ config['SITENAME'] }}</h1>
                <h2 class="subtitle">{% block mini %}{% endblock %}</h2>
            </div>
        </div>
    </section>

    {# Top navbar #}
    <nav class="navbar is-primary has-margin-bottom" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-brand">
                <a id="sidebar-toggle" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="nav-menu">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="nav-menu" class="navbar-menu">
                <div class="navbar-start">
                    {% for item in config.get('NAVBAR', []) %}
                        <a class="navbar-item" href="{{ item['link'] }}">{{ item['text'] }}</a>
                    {% else %}
                        <a class="navbar-item" href="/">{{ _('Home') }}</a>
                        <a class="navbar-item" href="{{ url_for('blog.index') }}">{{ _('Blog') }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </nav>

    {# Main content #}
    <section class="section">
        {% block content %}{% endblock %}
    </section>

    {# Show flash messages #}
    {{ macros.render_flash_messages() }}

    {# Footer #}
    <footer class="footer">
        <div class="container">
            <div class="columns">
                <div id="left-footer" class="column is-4">
                    {{ config.get('FOOTER_LEFT', '')|safe }}
                </div>
                <div id="right-footer" class="column is-4 is-offset-4">
                    {{ config.get('FOOTER_RIGHT', '')|safe }}
                </div>
            </div>
        </div>
    </footer>

    {# Cookie notice #}
    {% if config.COOKIE_CONSENT_SHOW %}
        {{ macros.cookie_consent() }}
    {% endif %}
</body>
{% endblock %}
</html>

akamatsu/templates/macros.html
{# Renders an input field #}
{% macro render_input(field, label="", placeholder="", size="", icon="", label_icon="", type="") %}
    {% if not label %}
        {% set label = field.label.text %}
    {% endif %}

    {% if size %}
        {% set size = "is-"+size %}
    {% endif %}

    <div class="field">
        {% if label %}
            <label class="label" for="{{ field.id }}">
                {% if label_icon %}
                    <span class="icon"><i class="fas fa-{{ label_icon }}"></i></span>
                {% endif %}
                <span>{{ label }}</span>
                <small class="is-pulled-right has-text-grey">{{ field.description }}</small>
            </label>
        {% endif %}

        {% if icon %}
            <div class="control has-icons-left">
                {% if type %}
                    {{ field(class_="input "+size, type=type) }}
                {% else %}
                    {{ field(class_="input "+size) }}
                {% endif %}

                <span class="icon is-small is-left">
                    <i class="fas fa-{{ icon }}"></i>
                </span>
            </div>

        {% else %}
            <div class="control">
                {% if type %}
                    {{ field(class_="input "+size, type=type) }}
                {% else %}
                    {{ field(class_="input "+size) }}
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endmacro %}


{# Renders a file field #}
{% macro render_file(field, label="", size="") %}
    {% if not label %}
        {% set label = field.label.text %}
    {% endif %}

    {% if size %}
        {% set size = "is-"+size %}
    {% endif %}

    <div class="field">
        <div class="file has-name is-fullwidth {{ size }}">
            <label class="file-label">
                {{ field(class_="file-input")}}

                <span class="file-cta">
                    <span class="file-icon">
                        <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label">{{ label }}</span>
                </span>
                <span class="file-name">{{ _('Nothing selected') }}</span>
            </label>
        </div>
    </div>
{% endmacro %}


{# Renders a date field

Available calendar types:
- datetime
- date
- time
#}
{% macro render_date_input(field, calendar_type='datetime', label="", label_icon="") %}
    {% if not label %}
        {% set label = field.label.text %}
    {% endif %}

    {% set cal_class = 'calendar-datetime' %}

    {% if calendar_type == 'date' %}
        {% set cal_class = 'calendar-date' %}

    {% elif calendar_type == 'time' %}
        {% set cal_class = 'time' %}
    {% endif %}

    <div class="field">
        {% if label %}
            <label class="label" for="{{ field.id }}">
                {% if label_icon %}
                    <span class="icon"><i class="fas fa-{{ label_icon }}"></i></span>
                {% endif %}
                <span>{{ label }}</span>
                <small class="is-pulled-right has-text-grey">{{ field.description }}</small>
            </label>
        {% endif %}

        <div class="control">
            {{ field(class_="input " + cal_class, type="text") }}
        </div>
    </div>
{% endmacro %}


{# Renders a number input field #}
{% macro render_number_input(field, label="", placeholder="", size="", icon="", min=1, max=0) %}
    {% if not label %}
        {% set label = field.label.text %}
    {% endif %}

    {% if size %}
        {% set size = "is-"+size %}
    {% endif %}

    {% if label %}
        {% if icon %}
            <label class="label" for="{{ field.id }}">
                <span class="icon"><i class="fas fa-{{ icon }}"></i></span>
                <span>{{ label }}</span>
                <small class="is-pulled-right has-text-grey">{{ field.description }}</small>
            </label>
        {% else %}
            <label class="label" for="{{ field.id }}">
                <span>{{ label }}</span>
                <small class="is-pulled-right has-text-grey">{{ field.description }}</small>
            </label>
        {% endif %}
    {% endif %}

    <div class="field has-addons has-addons-centered">
        <p class="control is-expanded">
            {{ field(class_="input "+size, type="number", min=min) }}
        </p>

        <p class="control">
            <a class="button num-sub">
                <span class="icon"><i class="fas fa-minus"></i></span>
            </a>
        </p>

        <p class="control">
            <a class="button num-add">
                <span class="icon"><i class="fas fa-plus"></i></span>
            </a>
        </p>
    </div>
{% endmacro %}


{# Renders a tag input field #}
{% macro render_tag_input(field, label="", placeholder="", size="", icon="") %}
    {% if not label %}
        {% set label = field.label.text %}
    {% endif %}

    {% if size %}
        {% set size = "is-"+size %}
    {% endif %}

    <div class="field">
        {% if label %}
            {% if icon %}
                <label class="label" for="{{ field.id }}">
                    <span class="icon"><i class="fas fa-{{ icon }}"></i></span>
                    <span>{{ label }}</span>
                    <small class="is-pulled-right has-text-grey">{{ field.description }}</small>
                </label>
            {% else %}
                <label class="label" for="{{ field.id }}">
                    <span>{{ label }}</span>
                    <small class="is-pulled-right has-text-grey">{{ field.description }}</small>
                </label>
            {% endif %}
        {% endif %}

        <div class="control">
            {{ field(class_="input "+size, type="tags") }}
        </div>
    </div>
{% endmacro %}


{# Renders a textarea field #}
{% macro render_textarea(field, label="", placeholder="", size="", icon="") %}
    {% if not label %}
        {% set label = field.label.text %}
    {% endif %}

    {% if size %}
        {% set size = "is-"+size %}
    {% endif %}

    <div class="field">
        {% if label %}
            {% if icon %}
                <label class="label" for="{{ field.id }}">
                    <span class="icon"><i class="fas fa-{{ icon }}"></i></span>
                    <span>{{ label }}</span>
                    <small class="is-pulled-right has-text-grey">{{ field.description }}</small>
                </label>
            {% else %}
                <label class="label" for="{{ field.id }}">
                    <span>{{ label }}</span>
                    <small class="is-pulled-right has-text-grey">{{ field.description }}</small>
                </label>
            {% endif %}
        {% endif %}

        <div class="control">
            {{ field(class_="textarea "+size) }}
        </div>
    </div>
{% endmacro %}


{# Renders a button/submit field #}
{% macro render_submit(field, label="", size="", color="primary", icon="", fullwidth=true) %}
    {% if not label %}
        {% set label = field.label.text %}
    {% endif %}

    {% if size %}
        {% set size = "is-"+size %}
    {% endif %}

    <div class="field">
        <div class="control">
            <button type="submit" class="button is-{{ color }} {{ size }} {% if fullwidth %}is-fullwidth{% endif %}">
                {% if icon %}
                    <span class="icon {{ size }}">
                        <i class="fas fa-{{ icon }}"></i>
                    </span>
                {% endif %}

                <span>{{ label }}</span>
            </button>
        </div>
    </div>
{% endmacro %}


{# Renders a select field #}
{% macro render_select(field, label="", size="", icon="", label_icon="", multiple=false, multiple_size=5) %}
    {% if not label %}
        {% set label = field.label.text %}
    {% endif %}

    {% if size %}
        {% set size = "is-"+size %}
    {% endif %}

    <div class="field">
        {% if label %}
            <label class="label" for="{{ field.id }}">
                {% if label_icon %}
                    <span class="icon"><i class="fas fa-{{ label_icon }}"></i></span>
                {% endif %}
                <span>{{ label }}</span>
                <small class="is-pulled-right has-text-grey">{{ field.description }}</small>
            </label>
        {% endif %}

        <div class="control {% if icon %}has-icons-left{% endif %}">
            {% if multiple %}
                <div class="select is-fullwidth is-multiple {{ size }}">
                    {{ field(size=multiple_size) }}
                </div>
            {% else %}
                <div class="select is-fullwidth {{ size }}">
                    {{ field() }}
                </div>
            {% endif %}

            {% if icon %}
                <div class="icon is-left">
                    <i class="fas fa-{{ icon }}"></i>
                </div>
            {% endif %}
        </div>
    </div>
{% endmacro %}


{# Renders a checkbox as a switch #}
{% macro render_switch(field, label="", size="", color="primary") %}
    {% if not label %}
        {% set label = field.label.text %}
    {% endif %}

    {% if size %}
        {% set size = "is-"+size %}
    {% endif %}

    <div class="field">
        {{ field(class_="switch is-rounded "+size+" is-"+color) }}
        <label for="{{ field.id }}">{{ label }}</label>
    </div>
{% endmacro %}


{# Renders a list of warnings for form fields #}
{% macro render_messages(messages, size="", color="warning") %}
    {% if size %}
        {% set size = "is-"+size %}
    {% endif %}

    <article class="message {{ size }} is-{{ color }}">
        <div class="message-body">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    </article>
{% endmacro %}


{# Render flash messages #}
{% macro render_flash_messages() %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <script type="text/javascript">
                {% for category, message in messages %}
                    showNotification('{{ category }}', '{{ message }}');
                {% endfor %}
            </script>
        {% endif %}
    {% endwith %}
{% endmacro %}


{# Renders pagination controls

Use kwargs for additional arguments for the URL. For instance:

    <a {% if pagination.has_next %}href="{{ url_for_self(page=pagination.page+1, search=kwargs['search'], sort=kwargs['sort'], order=kwargs['order']) }}"{% else %}disabled{% endif %} class="pagination-next">

Would render a link to the next page taking into account search arguments, sorting and ordering of a table.
#}
{% macro render_pagination(pagination) %}
    <nav class="pagination is-centered" role="navigation" aria-label="pagination" data-target="{{ target }}">
        <a {% if pagination.has_prev %}href="{{ url_for_self(page=pagination.page-1, sort=kwargs['sort'], order=kwargs['order']) }}"{% else %}disabled{% endif %} class="pagination-previous">
            <span class="icon"><i class="fas fa-chevron-left"></i></span>
            <span>{{ _('Previous') }}</span>
        </a>

        <a {% if pagination.has_next %}href="{{ url_for_self(page=pagination.page+1, sort=kwargs['sort'], order=kwargs['order']) }}"{% else %}disabled{% endif %} class="pagination-next">
            <span>{{ _('Next') }}</span>
            <span class="icon"><i class="fas fa-chevron-right"></i></span>
        </a>

        <ul class="pagination-list">
            {% for page in pagination.iter_pages() %}
                <li>
                    {% if page %}
                        {% if page != pagination.page %}
                            <a href="{{ url_for_self(page=page, sort=kwargs['sort'], order=kwargs['order']) }}"class="pagination-link">{{ page }}</a>
                        {% else %}
                            <a class="pagination-link is-current">{{ page }}</a>
                        {% endif %}

                    {% else %}
                        <span class="pagination-ellipsis">&hellip;</span>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </nav>
{% endmacro %}


{# Sortable table headers #}
{% macro sort_order(key, sort='date', order='desc') %}
    {% if key == sort %}
        {% if order == 'asc' %}
            <span class="icon"><i class="fas fa-chevron-up"></i></span>
        {% else %}
            <span class="icon"><i class="fas fa-chevron-down"></i></span>
        {% endif %}
    {% endif %}
{% endmacro %}

{# Show cookie notice #}
{% macro cookie_consent() %}
    <script>
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": "#363636"
                },
                "button": {
                    "background": "#3e8cc0"
                }
            },
            "position": "bottom-right",
            "content": {
            {% if config.COOKIE_CONSENT_MESSAGE_TEXT %}
                "message": "{{ config.COOKIE_CONSENT_MESSAGE_TEXT }}",
            {% endif %}
            {% if config.COOKIE_CONSENT_DISMISS_TEXT %}
                "dismiss": "{{ config.COOKIE_CONSENT_DISMISS_TEXT }}",
            {% endif %}
            {% if config.COOKIE_CONSENT_LINK_TEXT %}
                "link": "{{ config.COOKIE_CONSENT_LINK_TEXT }}",
            {% endif %}
            {% if config.COOKIE_CONSENT_LINK %}
                "href": "{{ config.COOKIE_CONSENT_LINK }}"
            {% endif %}
            }
        });
    </script>
{% endmacro %}